/// Flutter icons CustomAppIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///

import 'package:flutter/widgets.dart';

class CustomAppIcons {
  CustomAppIcons._();

  static const _kFontFam = 'CustomAppIcons';
  static const String? _kFontPkg = null;

  static const IconData instagram = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData free_code_camp = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leetcode = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
